#pragma once

#define USING_HIL 0

#define VCU_PRESENT 1

#define USING_ACTIVE_DISCHARGE_THROUGH_EMS 0
#define USING_TEMP_READINGS 0

#define USING_AIRGAPS_LIMIT 0

#define USING_CURRENT_ZEROING_LIMIT 0
#define USING_PEAK_CURRENT_PROTECTION 0
#define USING_EXTENDED_CURRENT_PROTECTION 0